// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {projects} from '../models';
import {scanner} from '../models';
import {process} from '../models';

export function DeleteCredential(arg1:string,arg2:string):Promise<void>;

export function DownloadBunPortable(arg1:string):Promise<string>;

export function GetEngineStatus():Promise<Record<string, any>>;

export function GetSystemInfo():Promise<core.SystemInfo>;

export function HasCredential(arg1:string,arg2:string):Promise<boolean>;

export function LimitResources(arg1:number,arg2:number,arg3:number):Promise<void>;

export function ListProjects():Promise<Array<projects.ProjectState>>;

export function LoadConfig():Promise<core.AppConfig>;

export function RegisterAndStartProject(arg1:scanner.ScanResult,arg2:process.RunConfig):Promise<string>;

export function RemoveProject(arg1:string):Promise<void>;

export function SaveConfig(arg1:core.AppConfig):Promise<void>;

export function SaveDefaultSettings(arg1:core.AppConfig):Promise<void>;

export function ScanProject(arg1:string):Promise<scanner.ScanResult>;

export function StartEphemeralTunnel(arg1:number):Promise<void>;

export function StartPermanentTunnel(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function StartProject(arg1:string):Promise<void>;

export function StopProject(arg1:string):Promise<void>;

export function StopTunnel():Promise<void>;

export function StoreCredential(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SyncVercel(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;
