// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LimitResources(arg1, arg2, arg3) {
  return window['go']['main']['App']['LimitResources'](arg1, arg2, arg3);
}

export function ScanProject(arg1) {
  return window['go']['main']['App']['ScanProject'](arg1);
}

export function StartTunnel(arg1) {
  return window['go']['main']['App']['StartTunnel'](arg1);
}

export function StopTunnel() {
  return window['go']['main']['App']['StopTunnel']();
}

export function SyncVercel(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SyncVercel'](arg1, arg2, arg3, arg4, arg5);
}
