// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCredential(arg1, arg2) {
  return window['go']['main']['App']['DeleteCredential'](arg1, arg2);
}

export function HasCredential(arg1, arg2) {
  return window['go']['main']['App']['HasCredential'](arg1, arg2);
}

export function LimitResources(arg1, arg2, arg3) {
  return window['go']['main']['App']['LimitResources'](arg1, arg2, arg3);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ScanProject(arg1) {
  return window['go']['main']['App']['ScanProject'](arg1);
}

export function StartEphemeralTunnel(arg1) {
  return window['go']['main']['App']['StartEphemeralTunnel'](arg1);
}

export function StartPermanentTunnel(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartPermanentTunnel'](arg1, arg2, arg3, arg4, arg5);
}

export function StopTunnel() {
  return window['go']['main']['App']['StopTunnel']();
}

export function StoreCredential(arg1, arg2, arg3) {
  return window['go']['main']['App']['StoreCredential'](arg1, arg2, arg3);
}

export function SyncVercel(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SyncVercel'](arg1, arg2, arg3, arg4, arg5);
}
